"""Personal Memory System v0.1 -- Phase 1: unified memory model + SQLite foundation.

Public API::

    from personal_memory import Database, MemoryRepository, Memory, Source

    repo = MemoryRepository(Database("data/memory.db"))
    source = repo.create_source(Source.create(source_type="text", title="t", content="c"))
    memory = repo.create_memory(Memory.create(
        type="knowledge", title="t", content="c", information_origin="source_content"))
    repo.link(memory.id, source.id)

Scope of Phase 1: models, validation, SQLite schema/migrations, CRUD, the
Source<->Memory relation, persistence, automated tests.  No LLM, extraction,
FTS5, embeddings, RAG, imports or UI.
"""

from __future__ import annotations

__version__ = "0.9.0"
__phase__ = "kb-1.0-phase-4"

from .capture import (  # noqa: E402
    CAPTURED_FROM_DEFAULT,
    CaptureRequest,
    CaptureResult,
    CaptureService,
)
from .db import (  # noqa: E402
    DEFAULT_DB_PATH,
    ENV_DB_PATH,
    MIGRATIONS,
    SUPPORTED_SCHEMA_VERSION,
    Database,
    Migration,
    MigrationReport,
    resolve_db_path,
)
from .errors import (  # noqa: E402
    ConflictError,
    IllegalTransitionError,
    DuplicateContentHashError,
    MemorySystemError,
    NotFoundError,
    ReferentialIntegrityError,
    SchemaError,
    ValidationError,
)
from .models import (  # noqa: E402
    CURRENT_SCHEMA_VERSION,
    coerce_enum,
    InformationOrigin,
    Memory,
    MemoryStatus,
    MemoryType,
    Source,
    SourceType,
    compute_content_hash,
    is_valid_timestamp,
    new_memory_id,
    new_source_id,
    normalize_content,
    utcnow_iso,
)
from .importers import (  # noqa: E402
    ALLOWED_CONTENT_TYPES,
    MAX_WEB_BYTES,
    BlockedUrlError,
    ContentEncodingError,
    EmptyContentError,
    InvalidUrlError,
    ResponseTooLargeError,
    UnsupportedContentTypeError,
    UrlFetchError,
    WebDocument,
    WebImportError,
    WebImporter,
    WebImportResult,
    assert_public_url,
    import_web_url,
    normalise_url,
    CHAT_EXTENSIONS,
    MAX_CHAT_BYTES,
    MAX_FILE_BYTES,
    ChatConversation,
    ChatImportError,
    ChatImporter,
    ChatImportResult,
    # NOTE: the importer's ``ChatMessage`` is deliberately NOT re-exported here -- the
    # name belongs to Phase 2's LLM request message (``personal_memory.ChatMessage``).
    # Import chat structures from ``personal_memory.importers`` instead.
    ChatParseError,
    ChatRole,
    EmptyConversationError,
    UnsupportedChatRoleError,
    import_chat_file,
    parse_chat_json,
    parse_role_text,
    SUPPORTED_EXTENSIONS,
    EmptyFileError,
    FileEncodingError,
    FileImportError,
    FileImporter,
    FileMissingError,
    FileReadError,
    FileTooLargeError,
    ImportedDocument,
    ImportResult,
    NotAFileError,
    UnsupportedFileTypeError,
    clean_markdown,
    import_file,
)
from .extraction import (  # noqa: E402
    ExtractionError,
    ExtractionResult,
    ExtractionValidationError,
    FormationOutcome,
    FormationPolicy,
    MemoryDraft,
    MemoryFormationService,
    RawInput,
)
from .llm import (  # noqa: E402
    ChatMessage,
    HttpTransport,
    LLMClient,
    LLMConfig,
    LLMConfigError,
    LLMError,
    LLMRequest,
    LLMRequestError,
    LLMResponse,
    LLMResponseError,
    TruncatedResponseError,
    extract_json_object,
    load_config,
)
from .prompts import PROMPT_VERSION  # noqa: E402
from .retrieval import (  # noqa: E402
    DEFAULT_LIMIT,
    MAX_LIMIT,
    STATUS_ALL,
    STATUS_CHOICES,
    MemoryHit,
    MemoryRetriever,
    RetrievalError,
    RetrievalResult,
    SourceRef,
    build_match_expression,
    classify_token,
    tokenize,
)
from .lifecycle import (  # noqa: E402
    ALLOWED_TRANSITIONS,
    LIFECYCLE_STATUSES,
    DeleteReport,
    MemoryLifecycle,
    TransitionReport,
    allowed_transitions,
    can_transition,
)
from .quality import (  # noqa: E402
    RELATIONS,
    ConflictCheck,
    ConflictClassifier,
    ConflictClassificationError,
    ConflictVerdict,
    DuplicateCheck,
    DuplicateScan,
    LLMConflictClassifier,
    MemoryQualityGate,
    QualityDecision,
    QualityError,
    QualityReport,
    QualityPolicy,
    canonicalize_text,
    fingerprint_of,
    memory_fingerprint,
)
from .store import MemoryRepository, MemoryUnitOfWork  # noqa: E402
from .learning_models import (  # noqa: E402
    LEARNING_SCHEMA_VERSION,
    LearningSession,
    LearningState,
    SessionStatus,
    TeachingStage,
    UnderstandingLevel,
    new_learning_session_id,
)
from .learning_store import LearningRepository, LearningUnitOfWork  # noqa: E402
from .learning import LearningContext, LearningOverview, LearningService  # noqa: E402
from .teacher import (  # noqa: E402
    ALLOWED_ACTION_TYPES,
    FORBIDDEN_ACTION_TYPES,
    AbandonSessionAction,
    FinishSessionAction,
    RecordAssessmentAction,
    RecordLearningAction,
    TeacherAction,
    TeacherContext,
    TeacherTurnRequest,
    TeacherTurnResponse,
)
from .teacher_executor import SUPPORTED_ACTION_TYPES, TeacherActionExecutor  # noqa: E402
from .teacher_llm import (  # noqa: E402
    DEFAULT_PROMPT_BUILDER,
    TEACHER_PROMPT_VERSION,
    TEACHER_PROMPT_VERSION_V2,
    TEACHER_RESPONSE_SCHEMA,
    PromptPayload,
    TeacherLLMAdapter,
    TeacherModel,
    TeacherModelError,
    TeacherPromptBuilder,
    TeacherPromptV2Builder,
    validate_action_context,
)
from .teacher_runtime import TeacherRuntime, TeacherTurnResult  # noqa: E402
from .teacher_provider import TeacherProvider  # noqa: E402
from .teacher_agent import (  # noqa: E402
    DEFAULT_MAX_STEPS,
    MAX_STEPS_LIMIT,
    STOP_ACTION_TYPES,
    TeacherAgent,
    TeacherAgentResult,
)
from .teacher_application import TeacherApplication  # noqa: E402
from .web import WebContext, create_server  # noqa: E402

__all__ = [
    "__version__",
    "__phase__",
    "CURRENT_SCHEMA_VERSION",
    "DEFAULT_DB_PATH",
    "ENV_DB_PATH",
    "MIGRATIONS",
    "SUPPORTED_SCHEMA_VERSION",
    "Database",
    "Migration",
    "MigrationReport",
    "MemoryRepository",
    "MemoryUnitOfWork",
    "LEARNING_SCHEMA_VERSION",
    "LearningContext",
    "LearningOverview",
    "LearningRepository",
    "LearningService",
    "ALLOWED_ACTION_TYPES",
    "FORBIDDEN_ACTION_TYPES",
    "AbandonSessionAction",
    "FinishSessionAction",
    "RecordAssessmentAction",
    "RecordLearningAction",
    "TeacherAction",
    "TeacherContext",
    "TeacherTurnRequest",
    "TeacherActionExecutor",
    "SUPPORTED_ACTION_TYPES",
    "TeacherTurnResponse",
    "TEACHER_PROMPT_VERSION",
    "TEACHER_PROMPT_VERSION_V2",
    "DEFAULT_PROMPT_BUILDER",
    "TEACHER_RESPONSE_SCHEMA",
    "PromptPayload",
    "TeacherLLMAdapter",
    "TeacherModel",
    "TeacherModelError",
    "TeacherPromptBuilder",
    "TeacherPromptV2Builder",
    "validate_action_context",
    "TeacherRuntime",
    "TeacherTurnResult",
    "TeacherProvider",
    "DEFAULT_MAX_STEPS",
    "MAX_STEPS_LIMIT",
    "STOP_ACTION_TYPES",
    "TeacherAgent",
    "TeacherAgentResult",
    "TeacherApplication",
    "LearningState",
    "LearningSession",
    "LearningUnitOfWork",
    "SessionStatus",
    "TeachingStage",
    "UnderstandingLevel",
    "new_learning_session_id",
    "PROMPT_VERSION",
    "RawInput",
    "MemoryDraft",
    "ExtractionResult",
    "ExtractionError",
    "ExtractionValidationError",
    "FormationPolicy",
    "FormationOutcome",
    "MemoryFormationService",
    "LLMClient",
    "LLMConfig",
    "LLMError",
    "LLMConfigError",
    "LLMRequest",
    "LLMRequestError",
    "LLMResponse",
    "LLMResponseError",
    "TruncatedResponseError",
    "ChatMessage",
    "HttpTransport",
    "extract_json_object",
    "load_config",
    "MemoryRetriever",
    "RetrievalResult",
    "MemoryHit",
    "SourceRef",
    "RetrievalError",
    "DEFAULT_LIMIT",
    "MAX_LIMIT",
    "STATUS_ALL",
    "STATUS_CHOICES",
    "tokenize",
    "build_match_expression",
    "classify_token",
    "Source",
    "Memory",
    "SourceType",
    "MemoryType",
    "InformationOrigin",
    "MemoryStatus",
    "MemorySystemError",
    "ValidationError",
    "NotFoundError",
    "ConflictError",
    "DuplicateContentHashError",
    "ReferentialIntegrityError",
    "IllegalTransitionError",
    "SchemaError",
    "compute_content_hash",
    "coerce_enum",
    "normalize_content",
    "is_valid_timestamp",
    "new_source_id",
    "new_memory_id",
    "utcnow_iso",
    "resolve_db_path",
    "CaptureService",
    "CaptureRequest",
    "CaptureResult",
    "CAPTURED_FROM_DEFAULT",
    "FileImporter",
    "ImportedDocument",
    "ImportResult",
    "FileImportError",
    "FileMissingError",
    "NotAFileError",
    "UnsupportedFileTypeError",
    "EmptyFileError",
    "FileTooLargeError",
    "FileEncodingError",
    "FileReadError",
    "SUPPORTED_EXTENSIONS",
    "MAX_FILE_BYTES",
    "clean_markdown",
    "import_file",
    "ChatRole",
    "ChatConversation",
    "ChatImporter",
    "ChatImportResult",
    "ChatImportError",
    "ChatParseError",
    "UnsupportedChatRoleError",
    "EmptyConversationError",
    "import_chat_file",
    "parse_role_text",
    "parse_chat_json",
    "CHAT_EXTENSIONS",
    "MAX_CHAT_BYTES",
    "WebContext",
    "create_server",
    "WebImporter",
    "WebDocument",
    "WebImportResult",
    "WebImportError",
    "InvalidUrlError",
    "BlockedUrlError",
    "ContentEncodingError",
    "UrlFetchError",
    "ResponseTooLargeError",
    "UnsupportedContentTypeError",
    "EmptyContentError",
    "import_web_url",
    "normalise_url",
    "assert_public_url",
    "MAX_WEB_BYTES",
    "ALLOWED_CONTENT_TYPES",
    "MemoryLifecycle",
    "TransitionReport",
    "DeleteReport",
    "ALLOWED_TRANSITIONS",
    "LIFECYCLE_STATUSES",
    "allowed_transitions",
    "can_transition",
    "MemoryQualityGate",
    "QualityPolicy",
    "QualityReport",
    "QualityDecision",
    "QualityError",
    "ConflictClassificationError",
    "ConflictClassifier",
    "LLMConflictClassifier",
    "DuplicateCheck",
    "DuplicateScan",
    "ConflictCheck",
    "ConflictVerdict",
    "RELATIONS",
    "canonicalize_text",
    "memory_fingerprint",
    "fingerprint_of",
]
